export const dummyData = {
  currentUser: {
    name: "John Doe",
    role: "Premium Member",
    initials: "JD",
    walletBalance: 1250,
    cartCount: 3,
    notificationCount: 4,
  },
  dashboardStats: [
    {
      title: "Total Spend",
      value: "Rs 48,250",
      change: "+12.4%",
      tone: "primary",
      description: "Compared with last month",
    },
    {
      title: "Orders Delivered",
      value: "128",
      change: "+8 orders",
      tone: "success",
      description: "Strong repeat purchase trend",
    },
    {
      title: "Wishlist Saved",
      value: "34",
      change: "11 hot picks",
      tone: "accent",
      description: "Products saved for next drop",
    },
    {
      title: "Reward Balance",
      value: "2,860 pts",
      change: "Silver tier",
      tone: "dark",
      description: "Redeem on checkout",
    },
  ],
  quickActions: [
    { title: "Browse New Arrivals", copy: "Latest drops curated for your taste.", cta: "Explore Shop" },
    { title: "Track Active Orders", copy: "Review shipping progress and delivery updates.", cta: "View Orders" },
    { title: "Unlock Reward Deals", copy: "Use your wallet and points on premium picks.", cta: "Open Wallet" },
  ],
  featuredCollections: [
    {
      title: "Urban Motion",
      subtitle: "Minimal street essentials",
      itemCount: "18 products",
      accent: "from-brand-500 to-brand-300",
    },
    {
      title: "Executive Edit",
      subtitle: "Refined workday carry",
      itemCount: "12 products",
      accent: "from-ink-900 to-ink-700",
    },
    {
      title: "Weekend Escape",
      subtitle: "Travel-ready accessories",
      itemCount: "24 products",
      accent: "from-accent-400 to-brand-400",
    },
  ],
  recentOrders: [
    {
      id: "VLR-908812",
      item: "Velora Signature Backpack",
      date: "09 Apr 2026",
      status: "Delivered",
      amount: "Rs 4,999",
    },
    {
      id: "VLR-908645",
      item: "Noir Smart Watch Strap",
      date: "07 Apr 2026",
      status: "In Transit",
      amount: "Rs 1,899",
    },
    {
      id: "VLR-908301",
      item: "Leather Desk Organizer",
      date: "03 Apr 2026",
      status: "Processing",
      amount: "Rs 2,350",
    },
  ],
  notifications: [
    { title: "Flash deal unlocked", copy: "Extra 15% off on Urban Motion collection till midnight.", time: "2m ago" },
    { title: "Order shipped", copy: "Your Signature Backpack is now on the way.", time: "1h ago" },
    { title: "Rewards updated", copy: "You earned 320 new points on your last purchase.", time: "Yesterday" },
  ],
  orderFilters: ["All Orders", "Delivered", "In Transit", "Processing", "Cancelled"],
  orderSummary: [
    {
      label: "All orders",
      value: "128",
      note: "Across all recent purchases",
      tone: "primary",
    },
    {
      label: "Delivered",
      value: "92",
      note: "Smooth completed deliveries",
      tone: "success",
    },
    {
      label: "In transit",
      value: "21",
      note: "Actively moving to customers",
      tone: "accent",
    },
    {
      label: "Processing",
      value: "15",
      note: "Packed or preparing dispatch",
      tone: "dark",
    },
  ],
  orderHistory: [
    {
      id: "VLR-104982",
      status: "Delivered",
      item: "Velora Signature Backpack",
      category: "Travel Carry",
      date: "09 Apr 2026",
      eta: "Delivered on 11 Apr",
      price: 4999,
      payment: "UPI",
      quantity: 1,
      from: "Velora Central Warehouse",
      to: "Ahmedabad, Gujarat",
      accent: "from-brand-500/14 to-white",
    },
    {
      id: "VLR-104871",
      status: "In Transit",
      item: "Noir Smart Watch Strap",
      category: "Accessories",
      date: "07 Apr 2026",
      eta: "Expected by 13 Apr",
      price: 1899,
      payment: "Card",
      quantity: 2,
      from: "Mumbai Fulfillment Hub",
      to: "Ahmedabad, Gujarat",
      accent: "from-sky-500/14 to-white",
    },
    {
      id: "VLR-104722",
      status: "Processing",
      item: "Leather Desk Organizer",
      category: "Workspace",
      date: "03 Apr 2026",
      eta: "Packing in progress",
      price: 2350,
      payment: "Wallet + Card",
      quantity: 1,
      from: "Bengaluru Premium Studio",
      to: "Ahmedabad, Gujarat",
      accent: "from-amber-500/14 to-white",
    },
    {
      id: "VLR-104613",
      status: "Cancelled",
      item: "Urban Motion Sling",
      category: "Everyday Carry",
      date: "29 Mar 2026",
      eta: "Refund initiated",
      price: 2799,
      payment: "UPI",
      quantity: 1,
      from: "Delhi Dispatch Center",
      to: "Ahmedabad, Gujarat",
      accent: "from-rose-500/14 to-white",
    },
  ],
  collectionHighlights: [
    {
      title: "Urban Motion",
      subtitle: "Minimal carry for everyday movement",
      description: "Performance-driven essentials with clean silhouettes, matte hardware, and lightweight structure.",
      itemCount: "18 products",
      accent: "from-brand-500 to-indigo-400",
      cta: "Shop the edit",
    },
    {
      title: "Executive Edit",
      subtitle: "Sharper workday essentials",
      description: "Refined textures, structured forms, and premium desk-to-travel accessories for focused routines.",
      itemCount: "12 products",
      accent: "from-ink-900 to-slate-700",
      cta: "View collection",
    },
    {
      title: "Weekend Escape",
      subtitle: "Travel-ready utility pieces",
      description: "Compact organizers, soft-shell bags, and versatile carry pieces tuned for quick getaways.",
      itemCount: "24 products",
      accent: "from-accent-400 to-brand-400",
      cta: "Discover now",
    },
  ],
  collectionCategories: [
    { label: "Bags & Carry", itemCount: "36 styles", note: "Backpacks, slings, travel carry", accent: "bg-brand-50 text-brand-600" },
    { label: "Workspace", itemCount: "14 styles", note: "Desk organization and smart accessories", accent: "bg-emerald-50 text-emerald-600" },
    { label: "Wearables", itemCount: "21 styles", note: "Bands, straps, smart utility gear", accent: "bg-amber-50 text-amber-600" },
    { label: "Travel", itemCount: "19 styles", note: "Weekend kits and premium organizers", accent: "bg-ink-100 text-ink-700" },
  ],
  curatedDrops: [
    {
      title: "Signature Backpack",
      price: 4999,
      tag: "Best seller",
      note: "Structured profile with premium storage layout.",
      accent: "from-brand-500/16 to-white",
    },
    {
      title: "Noir Watch Strap",
      price: 1899,
      tag: "New drop",
      note: "Minimal strap design with all-day comfort.",
      accent: "from-violet-500/16 to-white",
    },
    {
      title: "Leather Desk Organizer",
      price: 2350,
      tag: "Editor pick",
      note: "Refined workspace utility with clean compartments.",
      accent: "from-amber-500/16 to-white",
    },
  ],
  seasonalCollections: [
    {
      title: "Monsoon Ready",
      copy: "Water-resistant materials and protected compartments for daily movement in unpredictable weather.",
    },
    {
      title: "Travel Smart",
      copy: "Modular packing and compact organization pieces for short premium trips.",
    },
    {
      title: "Desk Reset",
      copy: "Elegant accessories that make your workspace cleaner, quieter, and more intentional.",
    },
  ],
  shopFilters: ["All", "Bags", "Workspace", "Wearables", "Travel", "New"],
  catalogHighlights: [
    {
      label: "Live products",
      value: "92",
      note: "Curated premium inventory",
      tone: "primary",
    },
    {
      label: "New arrivals",
      value: "14",
      note: "Fresh this week",
      tone: "accent",
    },
    {
      label: "Fast shipping",
      value: "24h",
      note: "Across priority cities",
      tone: "success",
    },
  ],
  productCatalog: [
    {
      slug: "velora-signature-backpack",
      title: "Velora Signature Backpack",
      category: "Bags",
      price: 4999,
      originalPrice: 6499,
      tag: "Best seller",
      description: "Structured everyday backpack with premium internal organization and matte hardware.",
      accent: "from-brand-500/18 to-white",
    },
    {
      slug: "noir-smart-watch-strap",
      title: "Noir Smart Watch Strap",
      category: "Wearables",
      price: 1899,
      originalPrice: 2399,
      tag: "New",
      description: "Minimal strap design built for all-day comfort and a sharper wrist profile.",
      accent: "from-violet-500/18 to-white",
    },
    {
      slug: "leather-desk-organizer",
      title: "Leather Desk Organizer",
      category: "Workspace",
      price: 2350,
      originalPrice: 2999,
      tag: "Editor pick",
      description: "Premium desk utility for cables, tools, cards, and focused workspace routines.",
      accent: "from-amber-500/18 to-white",
    },
    {
      slug: "urban-motion-sling",
      title: "Urban Motion Sling",
      category: "Bags",
      price: 2799,
      originalPrice: 3299,
      tag: "Popular",
      description: "Compact sling engineered for quick access carry and lightweight movement.",
      accent: "from-sky-500/18 to-white",
    },
    {
      slug: "weekend-escape-kit",
      title: "Weekend Escape Kit",
      category: "Travel",
      price: 3599,
      originalPrice: 4599,
      tag: "Travel pick",
      description: "A modular organizer system designed for short premium trips and efficient packing.",
      accent: "from-emerald-500/18 to-white",
    },
    {
      slug: "executive-laptop-sleeve",
      title: "Executive Laptop Sleeve",
      category: "Workspace",
      price: 3199,
      originalPrice: 3899,
      tag: "Top rated",
      description: "Clean lined sleeve with reinforced corners and refined workday texture.",
      accent: "from-ink-900/14 to-white",
    },
  ],
  merchandisingNotes: [
    {
      title: "High-intent browsing",
      copy: "Group products by utility and lifestyle so the catalog feels curated instead of crowded.",
    },
    {
      title: "Premium conversion cues",
      copy: "Price anchoring, strong tags, and minimal copy help products feel elevated and easier to compare.",
    },
    {
      title: "Fast path to checkout",
      copy: "Every product card should support immediate action without forcing the user into extra friction.",
    },
  ],
  productDetailMap: {
    "velora-signature-backpack": {
      slug: "velora-signature-backpack",
      title: "Velora Signature Backpack",
      category: "Bags",
      price: 4999,
      originalPrice: 6499,
      tag: "Best seller",
      shortDescription: "Structured everyday backpack with premium internal organization and matte hardware.",
      description:
        "The Velora Signature Backpack is designed for premium everyday movement. It balances structured aesthetics with practical storage, quick-access compartments, and a silhouette that works across commute, work, and short travel routines.",
      gallery: ["Main View", "Interior Layout", "Material Close-up", "Side Profile"],
      rating: "4.9/5",
      reviews: "214 reviews",
      delivery: "Free express delivery by 13 Apr",
      stock: "In stock, ready to ship",
      points: "Earn 320 reward points",
      features: [
        "18L structured main compartment",
        "Dedicated laptop protection sleeve",
        "Water-resistant premium fabric shell",
        "Quick access top pocket and hidden passport section",
      ],
      specifications: [
        { label: "Material", value: "Water-resistant woven shell" },
        { label: "Capacity", value: "18 liters" },
        { label: "Weight", value: "980 grams" },
        { label: "Warranty", value: "1 year premium coverage" },
      ],
      trustNotes: [
        "7-day easy returns on unused items",
        "Premium packaging and authenticity seal",
        "Priority support for reward members",
      ],
    },
  },
  relatedProducts: [
    {
      slug: "urban-motion-sling",
      title: "Urban Motion Sling",
      category: "Bags",
      price: 2799,
      originalPrice: 3299,
      tag: "Popular",
      description: "Compact sling engineered for quick access carry and lightweight movement.",
      accent: "from-sky-500/18 to-white",
    },
    {
      slug: "weekend-escape-kit",
      title: "Weekend Escape Kit",
      category: "Travel",
      price: 3599,
      originalPrice: 4599,
      tag: "Travel pick",
      description: "A modular organizer system designed for short premium trips and efficient packing.",
      accent: "from-emerald-500/18 to-white",
    },
    {
      slug: "executive-laptop-sleeve",
      title: "Executive Laptop Sleeve",
      category: "Workspace",
      price: 3199,
      originalPrice: 3899,
      tag: "Top rated",
      description: "Clean lined sleeve with reinforced corners and refined workday texture.",
      accent: "from-ink-900/14 to-white",
    },
  ],
  cartItems: [
    {
      id: "cart-1",
      slug: "velora-signature-backpack",
      title: "Velora Signature Backpack",
      category: "Bags",
      variant: "Obsidian Black",
      price: 4999,
      originalPrice: 6499,
      quantity: 1,
      accent: "from-brand-500/16 to-white",
    },
    {
      id: "cart-2",
      slug: "noir-smart-watch-strap",
      title: "Noir Smart Watch Strap",
      category: "Wearables",
      variant: "Graphite",
      price: 1899,
      originalPrice: 2399,
      quantity: 2,
      accent: "from-violet-500/16 to-white",
    },
    {
      id: "cart-3",
      slug: "executive-laptop-sleeve",
      title: "Executive Laptop Sleeve",
      category: "Workspace",
      variant: "Slate Grey",
      price: 3199,
      originalPrice: 3899,
      quantity: 1,
      accent: "from-ink-900/12 to-white",
    },
  ],
  availableCoupons: [
    { code: "FIRST20", note: "Flat Rs 200 off on your order" },
    { code: "VELORA10", note: "Extra 10% off on premium accessories" },
  ],
  shippingBenefits: [
    "Free express shipping above Rs 4,999",
    "Reward points apply automatically at checkout",
    "Easy 7-day returns on unused products",
  ],
  checkoutAddresses: [
    {
      id: "addr-home",
      label: "Home",
      type: "Primary",
      name: "John Doe",
      line1: "B-302, Shantam Residency, Satellite Road",
      cityState: "Ahmedabad, Gujarat 380015",
      phone: "+91 98765 43210",
    },
    {
      id: "addr-work",
      label: "Studio",
      type: "Work",
      name: "John Doe",
      line1: "Level 6, Navratna Business Park, SG Highway",
      cityState: "Ahmedabad, Gujarat 380054",
      phone: "+91 98765 43210",
    },
  ],
  deliveryOptions: [
    {
      id: "express",
      label: "Express delivery",
      note: "Arrives by 13 Apr with premium priority handling",
      price: 0,
    },
    {
      id: "scheduled",
      label: "Scheduled delivery",
      note: "Choose a convenient drop-off slot tomorrow",
      price: 149,
    },
  ],
  paymentMethods: [
    {
      id: "upi",
      label: "UPI",
      note: "Instant secure payment through any UPI app",
      accent: "bg-brand-50 text-brand-600",
    },
    {
      id: "card",
      label: "Credit / Debit Card",
      note: "Pay securely with saved or new card details",
      accent: "bg-emerald-50 text-emerald-600",
    },
    {
      id: "wallet",
      label: "Wallet + Card",
      note: "Use wallet balance first, then split the rest",
      accent: "bg-amber-50 text-amber-600",
    },
  ],
  checkoutTrustNotes: [
    "All payments are protected with secure encrypted checkout",
    "You can review the full order before the final confirmation",
    "Reward credits and wallet usage are reflected instantly",
  ],
  walletSummary: [
    {
      title: "Wallet balance",
      value: "Rs 1,250",
      note: "Instantly usable across cart and checkout",
      tone: "primary",
    },
    {
      title: "Reward points",
      value: "2,860",
      note: "Silver tier members earn faster",
      tone: "success",
    },
    {
      title: "Active coupons",
      value: "04",
      note: "Ready to stack across categories",
      tone: "accent",
    },
  ],
  rewardTiers: [
    { label: "Bronze", spend: "Rs 0 - Rs 10k", active: false },
    { label: "Silver", spend: "Rs 10k - Rs 50k", active: true },
    { label: "Gold", spend: "Rs 50k+", active: false },
  ],
  walletCoupons: [
    {
      code: "FIRST20",
      title: "Welcome purchase unlock",
      note: "Flat Rs 200 off on your current basket.",
      accent: "from-brand-500 to-violet-500",
    },
    {
      code: "VELORA10",
      title: "Premium accessories deal",
      note: "10% extra off on selected straps and organizers.",
      accent: "from-emerald-500 to-emerald-300",
    },
    {
      code: "SHIPFREE",
      title: "Priority delivery benefit",
      note: "Free scheduled delivery on the next qualifying order.",
      accent: "from-ink-900 to-slate-700",
    },
  ],
  walletTransactions: [
    {
      id: "txn-1",
      title: "Wallet used on checkout",
      note: "Applied during Velora Signature Backpack order",
      amount: "-Rs 1,250",
      type: "debit",
      date: "09 Apr 2026",
    },
    {
      id: "txn-2",
      title: "Reward credit received",
      note: "Points converted after delivered order",
      amount: "+Rs 320",
      type: "credit",
      date: "07 Apr 2026",
    },
    {
      id: "txn-3",
      title: "Refund back to wallet",
      note: "Urban Motion Sling cancellation refund",
      amount: "+Rs 2,799",
      type: "credit",
      date: "29 Mar 2026",
    },
  ],
  walletInsights: [
    "Using wallet-first payment lowers checkout friction for repeat orders.",
    "Reward points are strongest when paired with curated collection campaigns.",
    "Coupon visibility inside wallet increases conversion more than hiding them in checkout.",
  ],
  notificationSummary: [
    {
      title: "Unread alerts",
      value: "04",
      note: "Require attention today",
      tone: "primary",
    },
    {
      title: "Order updates",
      value: "07",
      note: "Across active shipments",
      tone: "success",
    },
    {
      title: "Offers unlocked",
      value: "12",
      note: "Campaigns available now",
      tone: "accent",
    },
  ],
  notificationCenter: [
    {
      id: "notif-1",
      type: "Order",
      title: "Your Signature Backpack is out for delivery",
      copy: "Courier handoff is complete and your package is expected today before 8 PM.",
      time: "12m ago",
      unread: true,
    },
    {
      id: "notif-2",
      type: "Offer",
      title: "Extra 15% unlocked on Urban Motion collection",
      copy: "This premium offer stays active until midnight and stacks with selected wallet coupons.",
      time: "48m ago",
      unread: true,
    },
    {
      id: "notif-3",
      type: "Reward",
      title: "320 reward points were added to your balance",
      copy: "Your delivered order has been credited. You can use the updated balance right away.",
      time: "2h ago",
      unread: true,
    },
    {
      id: "notif-4",
      type: "Order",
      title: "Leather Desk Organizer is now being packed",
      copy: "Your workspace order has moved into the processing stage and is preparing for dispatch.",
      time: "Yesterday",
      unread: false,
    },
  ],
  notificationPromos: [
    {
      title: "Premium member reward window",
      copy: "Use wallet balance with VELORA10 for an extra edge on accessories this week.",
    },
    {
      title: "Scheduled delivery unlocked",
      copy: "Your last 3 orders qualify for smoother slot-based drop-offs at no extra cost.",
    },
    {
      title: "Collection drop reminder",
      copy: "Executive Edit gets refreshed tomorrow with new carry pieces and workspace gear.",
    },
  ],
  notificationPreferences: [
    "Order tracking alerts",
    "Wallet and reward updates",
    "Premium collection drops",
  ],
  profileSummary: [
    {
      title: "Member since",
      value: "2024",
      note: "Two years of premium activity",
      tone: "primary",
    },
    {
      title: "Saved addresses",
      value: "02",
      note: "Home and studio currently active",
      tone: "success",
    },
    {
      title: "Saved products",
      value: "34",
      note: "Wishlist items ready for revisit",
      tone: "accent",
    },
  ],
  profileDetails: {
    name: "John Doe",
    email: "john.doe@velora.club",
    phone: "+91 98765 43210",
    city: "Ahmedabad, Gujarat",
    memberType: "Premium Member",
    spendLevel: "Silver Tier",
  },
  profilePreferences: [
    { label: "Personalized recommendations", enabled: true },
    { label: "Priority sale alerts", enabled: true },
    { label: "SMS delivery updates", enabled: false },
  ],
  profileSecurity: [
    "Password last updated 22 days ago",
    "Two-step verification available but not enabled",
    "Recent sign-in from MacBook Pro · Ahmedabad",
  ],
  profileActions: [
    "Update personal details",
    "Manage addresses",
    "Review payment methods",
    "Download invoices",
  ],
  authHighlights: [
    "Priority access to premium collection drops",
    "Wallet, rewards, and saved cart sync across sessions",
    "Faster checkout with stored preferences and addresses",
  ],
  authStats: [
    { label: "Premium members", value: "12k+" },
    { label: "Avg. repeat order rate", value: "68%" },
    { label: "Secure checkout confidence", value: "99.9%" },
  ],
  registerHighlights: [
    "Create a synced account for orders, rewards, and wallet tracking",
    "Unlock curated drops, member-first pricing, and saved checkout flow",
    "Keep addresses, preferences, and premium collections connected",
  ],
  homeHighlights: [
    {
      title: "Editorial discovery",
      copy: "Collections and catalog experiences are designed to guide intent, not overwhelm it.",
    },
    {
      title: "Premium account system",
      copy: "Wallet, rewards, orders, and profile management stay connected inside one clean dashboard.",
    },
    {
      title: "Fast purchase flow",
      copy: "From product detail to cart and checkout, each step is tuned to reduce friction.",
    },
  ],
  homeMetrics: [
    { label: "Premium members", value: "12k+" },
    { label: "Curated products", value: "92" },
    { label: "Repeat customer rate", value: "68%" },
    { label: "Avg. delivery speed", value: "24h" },
  ],
  adminStats: [
    {
      title: "Revenue this month",
      value: "Rs 18.4L",
      change: "+9.8%",
      tone: "primary",
      description: "Compared with previous month",
    },
    {
      title: "Orders pending review",
      value: "26",
      change: "8 urgent",
      tone: "accent",
      description: "Need fulfillment decisions",
    },
    {
      title: "Active customers",
      value: "4,892",
      change: "+312",
      tone: "success",
      description: "Users active in last 30 days",
    },
    {
      title: "Low stock SKUs",
      value: "11",
      change: "3 critical",
      tone: "dark",
      description: "Requires procurement follow-up",
    },
  ],
  adminQueues: [
    {
      title: "Product approval queue",
      copy: "7 new catalog items are waiting for copy, pricing, and image verification before publishing.",
      cta: "Manage products",
      to: "/admin/products",
    },
    {
      title: "Fulfillment exception queue",
      copy: "8 orders have payment, stock, or delivery exceptions that need a manual admin decision.",
      cta: "Manage orders",
      to: "/admin/orders",
    },
    {
      title: "User support queue",
      copy: "12 user tickets are linked to account, refund, or reward escalations.",
      cta: "Manage users",
      to: "/admin/users",
    },
  ],
  adminRecentActivity: [
    {
      title: "Signature Backpack inventory updated",
      copy: "Restock pushed 120 new units to the live catalog.",
      time: "18m ago",
    },
    {
      title: "Discount campaign approved",
      copy: "Urban Motion weekend offer scheduled for tomorrow morning.",
      time: "1h ago",
    },
    {
      title: "Refund escalation resolved",
      copy: "High-priority user issue marked complete by support lead.",
      time: "3h ago",
    },
  ],
  adminPanels: [
    {
      title: "Product management",
      note: "Catalog quality, inventory, and listing control",
      to: "/admin/products",
    },
    {
      title: "Order operations",
      note: "Fulfillment health, exceptions, and refunds",
      to: "/admin/orders",
    },
    {
      title: "User management",
      note: "Customer support, account reviews, and segments",
      to: "/admin/users",
    },
    {
      title: "Analytics",
      note: "Sales, conversion, and campaign performance",
      to: "/admin/analytics",
    },
    {
      title: "Discount engine",
      note: "Campaign creation and coupon orchestration",
      to: "/admin/discounts",
    },
  ],
  adminProductSummary: [
    {
      title: "Live listings",
      value: "92",
      note: "Currently visible in storefront",
      tone: "primary",
    },
    {
      title: "Draft products",
      value: "07",
      note: "Awaiting copy or pricing review",
      tone: "accent",
    },
    {
      title: "Low stock alerts",
      value: "11",
      note: "Requires inventory follow-up",
      tone: "success",
    },
  ],
  adminProducts: [
    {
      id: "prod-1",
      title: "Velora Signature Backpack",
      category: "Bags",
      price: "Rs 4,999",
      stock: "120 units",
      state: "Published",
      inventory: "Healthy",
      updatedAt: "09 Apr 2026",
    },
    {
      id: "prod-2",
      title: "Urban Motion Sling",
      category: "Bags",
      price: "Rs 2,799",
      stock: "09 units",
      state: "Published",
      inventory: "Low Stock",
      updatedAt: "08 Apr 2026",
    },
    {
      id: "prod-3",
      title: "Executive Laptop Sleeve",
      category: "Workspace",
      price: "Rs 3,199",
      stock: "46 units",
      state: "Draft",
      inventory: "Review Needed",
      updatedAt: "07 Apr 2026",
    },
    {
      id: "prod-4",
      title: "Weekend Escape Kit",
      category: "Travel",
      price: "Rs 3,599",
      stock: "21 units",
      state: "Published",
      inventory: "Healthy",
      updatedAt: "06 Apr 2026",
    },
  ],
  adminProductActions: [
    "Approve pending listings",
    "Restock low inventory items",
    "Refresh pricing and discount tags",
    "Review storefront product copy",
  ],
  adminOrderSummary: [
    {
      title: "Orders in exception",
      value: "08",
      note: "Need manual resolution",
      tone: "accent",
    },
    {
      title: "Refund requests",
      value: "14",
      note: "Awaiting admin approval",
      tone: "primary",
    },
    {
      title: "Fulfillment healthy",
      value: "91%",
      note: "Processed within SLA",
      tone: "success",
    },
  ],
  adminOrderQueue: [
    {
      id: "ord-1",
      orderId: "VLR-104871",
      customer: "Riya Shah",
      issue: "Payment split mismatch",
      status: "Needs Review",
      amount: "Rs 3,798",
    },
    {
      id: "ord-2",
      orderId: "VLR-104613",
      customer: "Aman Patel",
      issue: "Refund escalation",
      status: "Refund Pending",
      amount: "Rs 2,799",
    },
    {
      id: "ord-3",
      orderId: "VLR-105004",
      customer: "Neha Gupta",
      issue: "Delayed dispatch",
      status: "Priority",
      amount: "Rs 4,999",
    },
  ],
  adminUsersSummary: [
    {
      title: "Support escalations",
      value: "12",
      note: "Linked to user accounts",
      tone: "accent",
    },
    {
      title: "Premium members",
      value: "4,892",
      note: "Active in last 30 days",
      tone: "primary",
    },
    {
      title: "Retention score",
      value: "84%",
      note: "Healthy repeat engagement",
      tone: "success",
    },
  ],
  adminUsersList: [
    {
      id: "usr-1",
      name: "John Doe",
      segment: "Premium Member",
      status: "Active",
      spend: "Rs 48,250",
      note: "High-value repeat buyer",
    },
    {
      id: "usr-2",
      name: "Riya Shah",
      segment: "Silver Tier",
      status: "Support Case",
      spend: "Rs 19,880",
      note: "Refund issue needs follow-up",
    },
    {
      id: "usr-3",
      name: "Aman Patel",
      segment: "New Customer",
      status: "At Risk",
      spend: "Rs 6,120",
      note: "No repeat order in 45 days",
    },
  ],
  analyticsSalesData: [
    { label: "Jan", value: 34 },
    { label: "Feb", value: 46 },
    { label: "Mar", value: 51 },
    { label: "Apr", value: 68 },
    { label: "May", value: 72 },
    { label: "Jun", value: 84 },
  ],
  analyticsSpendingMix: [
    { label: "Wallet", value: 18, tone: "bg-brand-500" },
    { label: "Card", value: 51, tone: "bg-ink-900" },
    { label: "UPI", value: 31, tone: "bg-emerald-500" },
  ],
  analyticsPerformancePoints: [22, 38, 49, 44, 67, 72, 90],
  analyticsSummary: [
    {
      title: "Conversion uplift",
      value: "+6.4%",
      note: "Driven by improved product flow",
      tone: "primary",
    },
    {
      title: "AOV",
      value: "Rs 3,860",
      note: "Average order value this month",
      tone: "success",
    },
    {
      title: "Campaign ROI",
      value: "4.2x",
      note: "Across active discount windows",
      tone: "accent",
    },
  ],
  discountCampaigns: [
    {
      id: "dsc-1",
      code: "FIRST20",
      state: "Active",
      impact: "High",
      note: "Flat Rs 200 off on first purchase",
    },
    {
      id: "dsc-2",
      code: "VELORA10",
      state: "Scheduled",
      impact: "Medium",
      note: "10% off on premium accessories",
    },
    {
      id: "dsc-3",
      code: "SHIPFREE",
      state: "Active",
      impact: "Low",
      note: "Scheduled delivery unlocked at no cost",
    },
  ],
  quickBuyPicks: [
    {
      slug: "velora-signature-backpack",
      title: "Velora Signature Backpack",
      category: "Bags",
      price: 4999,
      originalPrice: 6499,
      tag: "Fast pick",
      description: "Top-selling premium carry ready for immediate checkout.",
      accent: "from-brand-500/18 to-white",
    },
    {
      slug: "urban-motion-sling",
      title: "Urban Motion Sling",
      category: "Bags",
      price: 2799,
      originalPrice: 3299,
      tag: "Fast pick",
      description: "Compact quick-access choice for lightweight everyday carry.",
      accent: "from-sky-500/18 to-white",
    },
  ],
  fareCalculatorPresets: [
    { label: "Single item order", value: "single" },
    { label: "Bundle checkout", value: "bundle" },
    { label: "Premium member basket", value: "premium" },
  ],
};
